version: '3.8'

services:
  support_bot:
    container_name: support_bot
    build: .
    env_file:
      - .env
    restart: "no"
    networks:
      - bot_network

networks:
  bot_network:
    name: support_bot_network
    driver: bridge 